replicaCount: 2
image:
  repository: ghcr.io/pranav7796/devopshomework/homework-api
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 8000
ingress:
  enabled: true
  className: nginx
  host: homework.local
resources:
  requests: {cpu: 100m, memory: 64Mi}
  limits: {cpu: 500m, memory: 256Mi}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
config:
  PORT: "8000"
secretName: homework-api-secret
database:
  enabled: true
  image: postgres:16-alpine
  storage: 1Gi
