services:
  multi-stage:
    build: ./multi-stage-build
    ports:
      - "8080:3000"

  nodejs:
    build: ./deployments/nodejs-app
    ports:
      - "8201:3000"

  python:
    build: ./deployments/python-app
    ports:
      - "8202:5000"

  java:
    build: ./deployments/java-app
    ports:
      - "8203:8080"
