apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-api
spec:
  ingressClassName: nginx
  rules:
    - host: homework.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homework-api
                port:
                  number: 80
